version: "3.1"
services:
  frontend:
    app:
      container_name: marvel-plan-app
      build: .
      volumes:
        - ./:/usr/src/app
      ports:
        - 3000:3000
      command: sh -c "tail -f /dev/null"
